<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="1" hostname="Nilesh-Bhavsar-25" failures="2" tests="2" name="Default test(failed)" time="0.262" errors="0" timestamp="2022-04-19T22:30:38 IST">
  <testcase classname="demo.TestNGRetryFailDemo" name="test2" time="0.059">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at demo.TestNGRetryFailDemo.test2(TestNGRetryFailDemo.java:16)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- test2 -->
  <testcase classname="demo.TestNGRetryFailDemo" name="test3" time="0.016">
    <failure type="java.lang.ArithmeticException" message="/ by zero">
      <![CDATA[java.lang.ArithmeticException: / by zero
at demo.TestNGRetryFailDemo.test3(TestNGRetryFailDemo.java:21)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- test3 -->
  <testcase classname="demo.TestNGRetryFailDemo" name="test1" time="0.0">
    <ignored/>
  </testcase> <!-- test1 -->
</testsuite> <!-- Default test(failed) -->
